In [ ]:
# step 1: Import libraries
import pandas  as pd
import numpy   as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import glob
print (glob.glob("*.csv"))

[]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Step 2: We read the dataset
df = pd.read_excel('/content/drive/MyDrive/Classroom/cafe_sales.xlsx')

In [ ]:
df.head (10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2,4,Credit Card,Takeaway,2023-08-09 00:00:00
1,TXN_4977031,Cake,4,3,12,Cash,In-store,5/16/2023
2,TXN_4271903,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,TXN_7034554,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,TXN_3160411,Coffee,2,2,4,Digital Wallet,In-store,2023-11-06 00:00:00
5,TXN_2602893,Smoothie,5,4,20,Credit Card,NaN,3/31/2023
6,TXN_4433211,UNKNOWN,3,3,9,ERROR,Takeaway,2023-06-10 00:00:00
7,TXN_6699534,Sandwich,4,4,16,Cash,UNKNOWN,10/28/2023
8,TXN_4717867,NaN,5,3,15,NaN,Takeaway,7/28/2023
9,TXN_2064365,Sandwich,5,4,20,NaN,In-store,12/31/2023

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [ ]:
import numpy as np
df.replace(['ERROR','UNKNOWN','unknown'],np.nan,inplace=True)

In [ ]:
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date    4202
dtype: int64

In [ ]:
df.head(20)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,NaN
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,5/16/2023
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,7/19/2023
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,4/27/2023
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,NaN
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,3/31/2023
6,TXN_4433211,NaN,3.0,3.0,9.0,NaN,Takeaway,NaN
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,NaN,10/28/2023
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,7/28/2023
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,12/31/2023
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,NaN
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,NaN
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,NaN
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,NaN
14,TXN_8915701,NaN,2.0,1.5,3.0,NaN,In-store,3/21/2023
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,11/15/2023
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,NaN
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2/24/2023
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,NaN,3/25/2023
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,1/15/2023

In [ ]:
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].str.strip()

In [ ]:
df['Quantity']=pd.to_numeric(df['Quantity'],errors='coerce')
df['Price Per Unit']=pd.to_numeric(df['Price Per Unit'],errors='coerce')
pd.to_numeric(df['Price Per Unit'],errors='coerce')

0       2.0
1       3.0
2       1.0
3       5.0
4       2.0
       ...
9995    2.0
9996    NaN
9997    2.0
9998    NaN
9999    4.0
Name: Price Per Unit, Length: 10000, dtype: float64

In [ ]:
df['total spent']=df['Quantity']*df['Price Per Unit']

In [ ]:
df['Transanction Date'] = pd.to_datetime(df['Transaction Date'],errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9031 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    6822 non-null   object
 6   Location          6039 non-null   object
 7   Transaction Date  5798 non-null   object
 8   total spent       9006 non-null   float64
dtypes: float64(4), object(5)
memory usage: 703.3+ KB

In [ ]:
df.head(20)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,total spent
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,NaN,4.0
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,5/16/2023,12.0
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,7/19/2023,4.0
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,4/27/2023,10.0
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,NaN,4.0
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,3/31/2023,20.0
6,TXN_4433211,NaN,3.0,3.0,9.0,NaN,Takeaway,NaN,9.0
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,NaN,10/28/2023,16.0
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,7/28/2023,15.0
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,12/31/2023,20.0
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,NaN,25.0
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,NaN,8.0
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,NaN,8.0
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,NaN,5.0
14,TXN_8915701,NaN,2.0,1.5,3.0,NaN,In-store,3/21/2023,3.0
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,11/15/2023,15.0
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,NaN,4.0
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2/24/2023,6.0
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,NaN,3/25/2023,15.0
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,1/15/2023,12.0

In [ ]:
df.to_csv('cleaned_cafe_sales.csv',index=False)